spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/bank_account
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
    jpa:
        properties.hibernate:
           show_sql: true
           format_sql: true
           liquibase.change-log: classpath:db/changelog/db.changelog-master.yaml